variables:
  FF_USE_FASTZIP: 1
  COMPOSER_CACHE_DIR: ${CI_PROJECT_DIR}/.composer-cache

default:
  image: gitlab.jtl-software.com:4567/connector/connector-utils/ci-docker/php/cli:8.1
  tags:
    - docker
  before_script:
    - composer update --no-interaction --no-progress
  cache:
    key: vendor
    policy: pull
    paths:
      - vendor
      - .composer-cache
      - composer.lock

include:
  - project: 'connector/connector-utils/CI-Templates'
    file: 'code-quality/ci.yaml'

stages:
  - cache
  - test
  - build

build_cache:
  stage: cache
  script:
    - echo
  cache:
    key: vendor
    policy: pull-push
    paths:
      - vendor
      - .composer-cache
      - composer.lock

code_quality:
  variables:
    CQ_FOLDERS: 'src/ bin/ extractor.php buildPhar.php'
  before_script: []

buildPhar:
  stage: build
  script:
    - php --define phar.readonly=0 buildPhar.php
  artifacts:
    paths:
      - extractor.phar
    expire_in: 1 day