name: Lint GitHub Actions

on:
  push:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
      - '.github/actionlint.yaml'
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
      - '.github/actionlint.yaml'

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: .github

      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
          fail_level: error
